CREATE TABLE mine (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE site (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mine_id BIGINT NOT NULL REFERENCES mine(id) ON DELETE CASCADE
);

CREATE TABLE shaft (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    site_id BIGINT NOT NULL REFERENCES site(id) ON DELETE CASCADE
);

CREATE TABLE area (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    shaft_id BIGINT NOT NULL REFERENCES shaft(id) ON DELETE CASCADE
);